id: P08805AF9
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: de
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    406d895b84624ebfa4f8ebbed21874d3:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    09d9492b0cfe4babba3bc4ba411d32b3:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    bed11babd4574cd2a7852ef974a9bb3d:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    4251b4bf5325419ba18e5a041e977386:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    d5f6d13c0beb4a74b5544dd2d228b79c:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    7646c6d022104610ad56671a891c52c3:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    5c4be8bc9e744732ab40dd0dd40f1899:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    43d5b46e4b0b465888933dde5dda7204:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    08109b7d495b4b008639601941714573:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    ea59becf2bcd4684bcc9cc1238db2d60:
      title: The Lament of Rudra
      parent: Confession
    7a825f60bd6a4b7ea77e05c99e68a609:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    00c4183921a747c8bc4ac65212b8eee1:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    d2360b432ba0401e8367879d4056c7b1:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    6a97f8acce9042b5942eaf0520380d46:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    ef1d1a670ca64482a315fd282c6d46df:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    c8a599e1bb004ba9a4b9815130f44fae:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    f67e1c662cc24ec48e9508e80ae0f53a:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    22d512bf944b4bb5b82bfde7879ae02a:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    8eac35c460f44ad1893d5a1f84da90b8:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    5d0cadbff2b64aeb9a7eb13af2638c7e:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    6184088b0db14e23891ac38244dc4ac5:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    643327786c4440b59bcdef4936a29f80:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    7effec7e06694ba29853a0321c2cdcc0:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    97169b56732f4d1a92cdabf22c638094:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    ff654620a3ac4fbd85bf6c847025bbc6:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    836cb979b5c14ba3991677bdd3cc2048:
      title: The Twenty-Eight Commitments
      parent: Tantra
    c7c3f06b1b264c418a5e29cbc0942423:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.940634'
last_modified_at: '2022-02-28T22:46:47.940637'
